### PR TITLE
Move dump_test_schema.pl dependencies from a README to a cpanfile feature

### PR DESCRIPTION
**Pull request by mkszuba**
### Description

Make it easier to install dependencies of _dump_test_schema.pl_ by having them declared in the cpanfile - in a separate feature because they introduce quite a few higher-order dependencies yet are  only useful to people who patch test databases in Ensembl repositories.

### Use case

Until now said dependencies were listed in _scripts/README.dump_test_schema_. This made it necessary for them to be installed by hand, moreover I suspect quite a few users didn't even know such a README file existed because it was stashed away in a subdirectory. Last but not least, the README seems slightly out of date.

### Benefits

Simplify installation of dependencies.

### Possible Drawbacks

Something new to learn to for people who have never worked with cpanfile features.

### Testing

_Have you added/modified unit tests to test the changes?_

No.

_If so, do the tests pass/fail?_

N/A

_Have you run the entire test suite and no regression was detected?_

Yes, no regression detected.

### CODE REVIEW

**Comment by markmcdowall** [comment]
@mkszuba could you have a look at the Travis report as there might be an issue with some of the dependencies during installation for perl 5.26

**Comment by markmcdowall** [comment]
@mkszuba could you have a look at the Travis report as there might be an issue with some of the dependencies during installation for perl 5.26

**Comment by mkszuba** [comment]
Looks like a problem with higher-order dependencies of Test::FTP::Server, unrelated to the PR at hand. Will try to take care of it with a separate pull request.

**Comment by nerdstrike** [comment]
Test::FTP::Server is a bit of a nightmare. It is showing its age.

**Pull request merged**
