### PR TITLE
More complete test that also checks that the years are correct

### PR DESCRIPTION
**Pull request by muffato**
(tested on ensembl-compara/master)

### CODE REVIEW

**Comment by magaliruffier** [comment]
looks neat, thanks
out of curiosity, how do you test it?

**Comment by muffato** [comment]
This is our unit-test: https://github.com/Ensembl/ensembl-compara/blob/master/modules/t/housekeeping_apache2.t
I've used it before and after updating the copyright statement for 2017 (and to find files that had been added with a wrong copyright)

**Comment by magaliruffier** [comment]
I might just steal that one off you ;-)

**Comment by premanand17** [comment]
Changes already in master by the following commit
(https://github.com/Ensembl/ensembl-test/commit/5a5f18b3d2775fb0efc46fc575445c28265f0253).

**Pull request closed without merging**
